name: Docker Image Build & Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u omikumari --password-stdin

      - name: Build Docker Image
        run: docker build -t omikumari/fastapi-docker-cd:latest .

      - name: Push Docker Image
        run: docker push omikumari/fastapi-docker-cd:latest
